services:
  - mongodb

language: php

php:
  - 5.6

before_install:
  - composer self-update
  - echo "yes" | pecl install apcu-4.0.11
  - echo "autodetect" | pecl install imagick
  - echo "yes" | pecl install mongo
  - pecl install mongodb

install:
  - composer install

script: ./vendor/bin/phpunit
