addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server

language: php

php:
  - 5.6

before_install:
  - sudo apt-get install -y mongodb-org
  - sudo apt-get install -y ffmpeg libavcodec-extra-53

  - mongod --version
  - mongodump --version
  - ffmpeg --version

  - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
  - echo memory_limit = -1 >> $INI_FILE;
  - echo session.gc_probability = 0 >> $INI_FILE;
  - echo opcache.enable_cli = 1 >> $INI_FILE;
  - composer self-update
  - echo "yes" | pecl install apcu-4.0.11
  - echo "autodetect" | pecl install imagick
  - echo "yes" | pecl install mongo

install:
  - composer install

script: ./vendor/bin/phpunit
